<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Scott_fa fa-trash-o</name>
   <tag></tag>
   <elementGuidId>25f5579d-78b1-40ed-b27a-ba8ab21fbee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1606939956065-0-uiGrid-000B-cell']/user-click-select/div/del-click/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash-o </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1606939956065-0-uiGrid-000B-cell&quot;)/user-click-select[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;avddbl&quot;]/del-click[1]/button[@class=&quot;btn btn-danger btn-xs&quot;]/i[@class=&quot;fa fa-trash-o&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1606939956065-0-uiGrid-000B-cell']/user-click-select/div/del-click/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//del-click/button/i</value>
   </webElementXpaths>
</WebElementEntity>
